# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78be692c80624157d94f46c372885ca2e1dc0e8959d0754e6a6de766c275e7d454190729e80973c3dc1777e88903b35b7bbf300a0f07233992b06af9b0856764

test:
  secret_key_base: 687bff98b66c056d6bf8a22d2f6ccbcb544011baad56ce8a64404d74a427fcddacc7e8d9a7e1efdae74c8c19fadc4c9d5cafda4f8a0a416b057c863c256eaa2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
